wandb_version: 1

n_hidden:
  desc: null
  value: 728
n_layers:
  desc: null
  value: 7
dropout:
  desc: null
  value: 0.2
agg:
  desc: null
  value: mean
batch_size:
  desc: null
  value: 128
num_partitions:
  desc: null
  value: 1024
lr:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687966677.803902
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.15.4
      8:
      - 5
