wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680670786.146751
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.10
      5: 0.14.0
      8:
      - 5
agg:
  desc: null
  value: mean
batch_size:
  desc: null
  value: 32768
budget:
  desc: null
  value: 5218
dropout:
  desc: null
  value: 0.7281864083255669
lr:
  desc: null
  value: 0.001
n_hidden:
  desc: null
  value: 1007
n_layers:
  desc: null
  value: 9
num_epochs:
  desc: null
  value: 2000
