wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680760390.141006
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 5
agg:
  desc: null
  value: gcn
batch_size:
  desc: null
  value: 512
dropout:
  desc: null
  value: 0.40929700854555406
lr:
  desc: null
  value: 0.002
n_hidden:
  desc: null
  value: 256
n_layers:
  desc: null
  value: 3
num_clusters:
  desc: null
  value: 100
num_epochs:
  desc: null
  value: 10
