wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680666753.695442
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 5
agg:
  desc: null
  value: gcn
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.7247308121181149
fanout:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.005
n_hidden:
  desc: null
  value: 1024
n_layers:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 10
