wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687964595.663249
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.15.4
      8:
      - 5
      - 9
